name: Update Github Stats

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate SVG
        run: |
          npx github-stats-terminal-style anis-mselmi dracula || echo "generation failed"

      - name: Check file
        run: |
          ls -la

      - name: Commit SVG
        run: |
          if [ -f github_stats.svg ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add github_stats.svg
            git commit -m "update stats" || echo "no changes"
            git push
          else
            echo "github_stats.svg not found ❌"
          fi
