name: Update Github Stats

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone generator repo
        run: |
          git clone https://github.com/yogeshwaran01/github-stats-terminal-style.git

      - name: Install dependencies
        run: |
          cd github-stats-terminal-style
          npm install

      - name: Build project
        run: |
          cd github-stats-terminal-style
          npm run build

      - name: Generate SVG
        run: |
          cd github-stats-terminal-style
          node dist/bin/github-stats-terminal.js anis-mselmi dracula
          cp github_stats.svg ../

      - name: Commit SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add github_stats.svg
          git commit -m "update stats" || echo "no changes"
          git push
